### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by tborychowski** [jakshin/open-in-iterm#2]
Hi,

Is there a plan to add a dark-themed icon for the macos mojave dark mode?

<img width="873" alt="screenshot 2018-07-20 at 14 22 59" src="https://user-images.githubusercontent.com/392513/43004697-8006867c-8c28-11e8-9e90-eb7faacf1f7c.png">

**Comment by jakshin** [comment]
I don't have a specific plan to support dark mode, but doing so sounds like a nice idea. I don't know much yet about how it works, though, or whether it's possible to make an app icon which automatically adapts to dark mode... worst case, there could just be 2 app icons, the current one for light mode and a tweaked one for dark mode, and the app could be built with whichever is preferred.

**Comment by tborychowski** [comment]
Yeah, I think that would be quite sufficient. I prefer dark mode and don't switch between themes at all.
So if there was dark-only version I'd be very happy 😀

**Comment by tborychowski** [comment]
Hi. I made the dark icon 😀
It's not perfect, and a bit different than yours (I couldn't get the font right and the background is still somehow different than one on finder native icons).
Anyway, here it is - if you'd like to use it.
Here's how it looks:
<img width="396" alt="screenshot 2018-08-02 at 09 12 58" src="https://user-images.githubusercontent.com/392513/43571203-44b775fc-9634-11e8-903c-b7f83c256a67.png">

and here's the icon:  [app-dark.zip](https://github.com/jakshin/open-in-iterm/files/2252680/app-dark.zip)

**Comment by tborychowski** [comment]
I updated the icon to match the new button style (the size and gradient has changed slightly):
[iterm.zip](https://github.com/jakshin/open-in-iterm/files/2580173/iterm.zip)

<img width="339" alt="screenshot 2018-11-14 at 09 59 09" src="https://user-images.githubusercontent.com/392513/48475287-60fc8b00-e7f4-11e8-9eb9-6d9a712700d0.png">

**Comment by jakshin** [comment]
Awesome, @tborychowski - that icon looks great in dark mode. Thank you!

I went ahead and tweaked the build script so the dark icon can be selected at build time. I'm still hoping to find a way to use a single icon which works in light or dark mode - and the light icon should be resized for Mojave too. But it's a bit complicated since I need to use High Sierra on some machines for a while, so those are tasks for a different day. Meanwhile I really appreciate your contribution.
